### ISSUE TITLE
[MANDATAIRE] Prise en compte des particularités des préposés

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1300]
## Constat
Aujourd'hui les proposés utilisent la même interface que celle des mandataires individuels. Il est nécessaire d'adapter leur interface afin de mieux correspondre à leurs spécificités.

## Besoins identifier
- [ ] Gérer la liste des établissements nationaux dans lesquels un préposé peut exercer
- [ ] Permettre de rattacher un proposé à un ou plusieurs établissements
- [ ] Permettre à un magistrat de filtrer par établissement
