### ISSUE TITLE
[MANDATAIRE][SERVICE] ne pas afficher par défaut les mesures éteintes

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1531]
## Constat
ETQ mandataire ou service, dans la page `mesures`, on affiche par défaut les mesures en cours et éteintes.
Il ne faudrait afficher que les mesures en cours par défaut avec la possibilité d'afficher les mesures éteintes

# TODO
Dans 'input `select` de la barre de filtre correspondant à l'état de la mesure:
- [x] enlever le choix `vide`
- [x] sélectionner par défaut les mesures dans l'état `Mesure en cours`
- [x] reprendre la query pour l'état soit obligatoire
