### ISSUE TITLE
[SERVICE] Ajout du Siret pour les service

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1550]
## Constat
Il a été décidé avec les éditeurs d'utiliser le `siret` comme identifiant des services

Il est donc nécessaire de rajouter cette données en base de données et de la gérer dans les formulaires de création / modification d'un service

## TODO
- [x] ajouter en base de données, une colonne `siret` dans `services`. Cette colonne est `unique`; On utilise `knex` pour les migrations. voir le répertoire `packages/knex/migration_v2`
- [x] Dans l'admin, ajouter un champs `Siret` en obligatoire dans les formulaires de création d'un service
- [ ] Utiliser l'API SIRET pour remplir les champs du formulaire à la création

le Siret doit respecter le pattern `\\d{14}$`

**Comment by tglatt** [comment]
@remiroyc , as-tu commencé, l'issue? Si ce n'est pas le cas, il faut ajouter le Siret uniquement sur les services.

Après un retour d'un éditeur, il semblerait que toutes les antennes n'ont pas de Siret. Il va falloir trouver un autre identifiant intéropérable.

**Comment by remiroyc** [comment]
J'ai commencé a regarder un peu l'issue mais j'ai pas commencé a coder encore. On peut en parler au daily si tu veux.

**Comment by tglatt** [comment]
@remiroyc , j'ai enlevé les taches sur les antennes. Du coup, tu peux aussi prendre ce ticket

**Comment by tglatt** [comment]
@gershon , concernant le dernier point 

```txt
Utiliser l'API SIRET pour remplir les champs du formulaire à la création
```

On a encore besoin de tester l'API SIRENE avant de l'utiliser à plusieurs endroits. Il y a des choses que je ne comprends pas avec dans les imports....

Si tu n'as commencé à avancer sur ce point, je serais d'avis de s'arrêter la sur ce ticket.
