### ISSUE TITLE
[PREPOSE] ETQ preposé je peux renseigner les établissements dans lesquels je travaille

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1563]
## Objectif
- Un préposé doit pouvoir renseigner les établissements dans lesquels il travaille.

## TODO `database`
- [ ] supprimer toutes les entrée dans `mandataire_etablissement`
- [ ] supprimer toutes les entrée dans `etablissements`
- [ ] ajouter `departement_id` dans `etablissements` en `NOT NULL`
- [ ] ajouter `siret` dans `etablissements` en `NOT NULL` et `unique`

## TODO `prepose`
- [ ] Dans `Vos informations`, ajouter un panneau `Vos établissements` sous `Informations générales`.
- [ ]  le composant `Vos établissements` est composé de 2 éléments:
  - une première ligne avec un input et un bouton `Ajouter`
  - Dessous, un tableau avec la liste des établissements du `prepose`, table `mandataire_etablissement`
- [ ] **Comportement de l'input**: Le préposé rentre un numéro de Siret et clique sur le bouton `ajouter`:
 - Si on retrouve l'établissement correspondant au SIRET dans notre base de données, on l'ajoute
 - Sinon, on interroge, l'API SIRENE `https://entreprise.api.gouv.fr`
```bash
-- SIRET: 26310012500016
curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer a8d6c5c5-8ffc-34c6-b2fd-e2a725c413b1' 'https://api.insee.fr/entreprises/sirene/V3/siret/26310012500016'
```
- Si l'API ne retourne rien, on affiche un message
- [ ]  **La liste des établissements**, si on clique sur un établissement, on affiche les informations de l'établissements dans une nouvelle page. A partir, de cette page, le préposé doit pouvoir supprimer un établissement
