### ISSUE TITLE
[INDIVIDUEL] Ajouter des onglet dans la 'Vos informations'

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#1610]
## Métier
Dans le cadre des enquêtes annuelles de la DGCS, nous devons collecter des données sur le mandataire individuel:
- Informations générales
- Agrément
- Modalité d'exercice
- Formation et niveau de qualification

## TODO
Ajouter des onglets dans la page `mandataire/informations` 
- [ ] Un onglet "Informations générales". On placera le contenu actuel de la page `mandataire/informations`  dans cette onglet
- [ ] Un onglet "Agrément" #1609
- [ ] Un onglet "Modalité d'exercice"
- [ ] Un onglet "Formation"
