### ISSUE TITLE
API editeur > codes postaux

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#2339]
>Il y a un problème sur le gestion des codes postaux, l’API refuse les codes postaux qui ne sont pas 5 numériques mais
Les pays limitrophes comme la Belgique et le Luxembourg n’ont que 4 chiffres dans le code postal.
Ils sont parfois saisis sous la forme BXXXX et LXXXX, ayant vécu au Luxembourg ce sont des formats accepté par leurs système postaux.
Cela ne me dérange pas de filtrer la lettre pour n’avoir que les 4 chiffres mais il faut que le système les accepte.

### TODO

nous devons gérer cela à tous les points de création / modification d'une mesure:
- [x] création / modification via l'UI par un mandataire
- [x] import via un csv
- [x] création / modification par l'API éditeur
- [ ] import via  OCMI **à gérer dans la PR correspondante à l'import via OCMI**

**Comment by tglatt** [comment]
fix by https://github.com/SocialGouv/emjpm/pull/2381
