### ISSUE TITLE
Tableau d'imports

### ISSUE THREAD

**Issue by coraliepelletier** [SocialGouv/emjpm#657]
En tant que mandataires (individuels, services, préposés d'établissements) je souhaite pouvoir importer mes mesures via un tableau EXCEL lors de la création de mon profil.
En tant que mandataire, je veux une présentation plus claire de la page d'import afin de comprendre facilement et rapidement comment créer le fichier d'import 

## Contexte et problématique
Au moment de la création de profil d'un mandataire, une fonctionnalité eMJPM permet aux utilisateurs d'importer l'ensemble de leurs mesures en une fois de manière automatique et non manuelle. 

Cet import n'est pas fonctionnel :
* les intitulés des colonnes ne sont pas porteurs de sens pour les utilisateurs qui se trompent dans le remplissage
* les contenus ne sont pas fixés, les utilisateurs ne respectent pas toujours les bons formats
* les numéros RG ne sont pas pris en compte lors d'un import

Il y a plusieurs problèmes identifiés par l'équipe :
1. les consignes de remplissage des tableaux présentes sur la page "imports" ne sont pas claires : la présentation du tableau n'aide pas à la compréhension (horizontal sur la page imports, vertical dans la version à transmettre par les mandataires). la page import actuelle est peu lue et comprise : trop de texte ;  trop technique ; trop théorique, manque d'exemple
2. les tableaux d'imports ne reprennent pas exactement les mêmes données que les tableaux affichés sur la plateforme
3. les tableaux issus des logiciels métier ne sont pas conformes au template eMJPM, or les mandataires ne retravaillent pas les tableaux issus de leur logiciel métier avant de l'importer sur la plateforme eMJPM

## Utilisateurs
mandataires (individuels, services, préposés d'établissements)

## Résultat souhaité
* les tableaux d'imports de mesures doivent reprendre toutes les informations nécessaires pour compléter (complètement) les colonnes de eMJPM
* les importations Excel doivent prendre en compte les tribunaux de rattachement 
* les numéros RG des mesures doivent être prises en compte dans les tableaux d'import des données
* les tableaux d'imports doivent pouvoir indiquer le type de mesures importées

### 1. Refonte du tableau d'import
Je souhaite pouvoir renseigner les Tribunaux qui m'ont attribué la mesure pour chaque mesure. 
Je souhaite que l'importation Excel prenne en compte cette donnée (nouvelle colonne)

### 2. Refonte page imports (explications en ligne)
ajouter du texte + explicite et facile
ajotuer une image exemple
ajotuer le fichier modèle
et la note explicative

### 3. Demander aux logiciels métier de produire des tableaux Excel au format eMJPM
voir explications SLITE : https://emjpm.slite.com/app/filters/all/notes/a8mFP0uNEl 

## Maquettes
- maquette figma (à mettre à jour) : https://www.figma.com/file/CBAUyrwBjIqWqPkir6SHxTKN/Import-e-MJPM?node-id=4%3A4

![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/5596f872-ee57-4bd6-b59b-b42521e91abb)

- tableau exemple avec explication : 
![image.png](https://images.zenhubusercontent.com/5d08d1b71846cf166d66b45f/c07a5596-708b-4435-9f84-21ca6a664243)

- fichier modèle : https://drive.google.com/open?id=19ukOW4tT7bUmSPr2erd-xIA0Phv3pnlHz_R9ksGgWbY

- notice d'utilisation : https://trello-attachments.s3.amazonaws.com/5ae1d4c1ec15c70d6fc31e7c/5c065d1245f9a66a1d15976e/843c14c7507777f448b064529fad1d70/Notice_d_utilisation_de_l_importation.pdf

## Critères d'acceptation
- [ ] les imports sont fonctionnels : pas de message d'erreur pour les utilisateurs et les données s'implémentent correctement (les demandes de supports sur ce sujet diminuent)
- [ ] les données sont toutes prises en compte, toutes les colonnes sont remplies après imports
- [ ] les tableaux des logiciels métier correspondent à notre demande et ils sont efficacement intégrés à la plateforme

**Comment by coraliepelletier** [comment]
Les prochaines étapes de travail :
1. Refonte du tableau et des explications @Jasminemeurin et @melanie57 
2. Contact avec les logiciels métier @coraliepelletier et @kwiss 
3. Rédaction US sur les importations automatiques de données @coraliepelletier
