### ISSUE TITLE
[REVIEW] Todo de la review du 19 novembre

### ISSUE THREAD

**Issue by tglatt** [SocialGouv/emjpm#990]
- [ ] Import service: communication éditeur
- [ ] Service: structuration des services
- [x] OCMI: Récupération de la documentation de l'export et la communiquer au utilisateur
- [ ] Changement de mot de passe: tester la modification des mot de passe pour tous les comptes

- [ ] Service > Renseigner capacité max et disponibilité pour les services avant import
- [ ] Validation du mail à envoyer aux mandataires individuels avant import => 10 décembre
